### ISSUE TITLE
Mapping to toastr rev

### ISSUE THREAD

**Issue by TimFerrell** [Foxandxss/angular-toastr#111]
@Foxandxss - is there any way to establish a revision of angular-toastr and toastr?

Does such a thing exist already? I'm one of the maintainers of the toastr project, and I'd like to gain an understanding of the relationship between our projects.

**Comment by Foxandxss** [comment]
Excuse me, what do you mean with "Establish a revision"? Sometimes I get lost with some english expressions.

**Comment by TimFerrell** [comment]
Sorry, I probably could've asked that more clearly. I would like to understand the relationship between the standalone toastr project, and the one that you maintain. 

Toastr has version numbers, and it appears that your fork also has version numbers, but I am trying to identify is there is anyway to see the version of original toastr code that you have applied to your fork. 

For example, you have tag 1.4.1 as the most recent tag in your repo. Is there anyway, given your tagging system that I could identify what version of toastr is used in that tag?

**Comment by Foxandxss** [comment]
I liked the original toastr and one day I decided to port it to Angular for fun and also to remove jQuery. The idea was to grab the API that toastr had 1 year ago and port it back to Angular so it could be a drop-in replacement.

If I remember correctly I managed to port a great chunk of functionality so I released 0.0.1.

Since then I started to fix bugs and to implement the remaining parts.

This library started to get used more and more, asking more features and some changes. I always managed to stay on what the original toastr does. Also some features that are more on the angular side (like custom templates and stuff). When it was stable enough I released 1.0.0.

After that and to be honest, I lost track of what you guys were doing and I started to implement what people needed, stuff like hooks (onClose, onShow), limited the number of toasts opened, prevent duplicates and other stuff.

In fact, I remember that someone said once "hey, we also want that nice progressBar" and I said.. uh? And there it was, I never realized it so I ported that as well.

So as today, I try to implement all the things you guys does but I also need to be up to date with what the users ask me to do. But the real truth is that what people ask me to do and the bugs that comes time to time had me busy enough to ever look the original toastr again.

So to answer your question, there is no match versions of codeseven toastr with my toastr.

**Comment by Foxandxss** [comment]
Maybe I should change my readme to say that it was originally a port of CodeSeven/toastr?

I am open to ideas ;)

**Comment by TimFerrell** [comment]
That clears a lot up, thanks for the answer.

If you're interested, we are re-architecting toastr to make more applicable to current developer needs. 

Check out the thread here: https://github.com/CodeSeven/toastr/issues/217
And the branch here: https://github.com/CodeSeven/toastr/tree/v3

While the goal isn't to make an angular directive, we do aim to remove jQuery and use CSS/WebAnimations rather than jQuery animations among other things. Given your experience, I think you'd be a valuable contributor.

**Comment by Foxandxss** [comment]
That is a good movement now that big frameworks seems to be walking away from jQuery. Would make `toastr` a much better life.

This brings an interesting discussion. I had in mind a port for angular 2 (once the api freezes), but since Angular 2 is not "picky" anymore with third party stuff, toastr v3 could be enough for Angular 2, without the need of a library like mine. I don't think of any reason to not be able to inject that new Toastr class as an injection in Angular 2.

Said that, I need to put my effort in here so all my users are up to date with no issues whatsoever but I think that if I am not wrong regarding Angular 2, we could join forces to make Toastr usable in modern framework (angular 2, aurelia, react, etc) with no effort or with a minimal wrapper.

**Comment by TimFerrell** [comment]
Sounds good.
