### ISSUE TITLE
cleanOptionsOverride(options) function deletes some options before toast creation

### ISSUE THREAD

**Issue by paulshatalov** [Foxandxss/angular-toastr#120]
Why is it done this way? Seems that is why my top-center toasts shown only in one position - top-right. If I remove using this function in createToast() - it works properly.

Thanks in advice.

**Comment by Foxandxss** [comment]
I am not sure if I understand your first problem (top-center toasts shown only in one position).

The reason I clean some options for concrete toasts is because they can't be used in concrete toast and if some of them could case weird behavior.

The reason I filter the position out it is because the position goes into the container and not in the toasts.

So when you show a toast for the first time, a container is created with the desired position. After all toasts are gone, the container is destroyed so you can then swap the position for the next serie of toasts.

**Comment by paulshatalov** [comment]
Thanks for you comment, Jesús.

"toasts shown only in one position" - let me describe.
I configure a new toast with top-center position, but when toast appears its position is default (top-right). So I made a little research of you code and find out what cleanOptionsOverride() function clear all bad options (include position) _before_ toast created. Seems this is why I can't set position to my toasts. Or I'm wrong?

**Comment by Foxandxss** [comment]
Yeah, let me explain the process of what you do:

(Default options):

-> You open a toast and set in its option that you want `top-center`.
-> Toast position option is deleted
-> Container is created using the default option `top-right`.
-> Toast is shown in `top-right`.

If you monkey patch the function you get:

-> You open a toast and set in its option that you want `top-center`.
-> Container is created using the toast position option `top-center`.
-> Toast is shown in `top-center` (Because the container has been created with that position).
-> Before the previous toast hide (AKA container still alive) you create one with `top-left`.
-> Container is still alive with `top-center`, move to the next step
-> Toast is shown in `top-center` and not `top-left`.

So the position has nothing to do with toasts, the position is only for the container. The container is who decides where the toast gets positioned, so setting the option on the toast makes no changes, those options are meant to change the toast itself and not the container.

Removing the option doesn't fix the issue, it is only a side effect what you get.

To make this really working and letting the user pop different toast in different position, I would need to rewrite half library to let different container appear with different positions.

**Comment by paulshatalov** [comment]
So...can I just write
