### ISSUE TITLE
Does not work with HTTP Interceptor

### ISSUE THREAD

**Issue by svuser1** [Foxandxss/angular-toastr#127]
Following is my code in app

<code>
var app = angular.module("app",["ngAnimate", "toastr"]);

    var ModuleConfig = function  ($httpProvider) {
      $httpProvider.interceptors.push("BudsHTTPInterceptor");
    };

    var BudsHTTPInterceptor = function ($rootScope) {
      return {
          response: function(response) {
          console.log("Success - BudsHTTPInterceptor" + status);
        },
        responseError: function(response) {
          console.log("Error - BudsHTTPInterceptor" + status + JSON.stringify(response));
        }
      }
    };
    app.config(ModuleConfig);
    app.service("BudsHTTPInterceptor", BudsHTTPInterceptor);

    app.controller("MainCtrl",  ["$scope","toastr", function($scope,toastr){
	$scope.hello = "Hello world";
	$scope.user={};

      toastr.success('Hello world!', 'Toastr fun!');

    }]);	/*END MainCtrl */

<code>

I get the error

<code>

TypeError: Cannot read property 'data' of undefined
    at angular.js:16128
    at angular.js:13248
    at n.a.$get.n.$eval (angular.js:14466)
    at n.a.$get.n.$digest (angular.js:14282)
    at n.a.$get.n.$apply (angular.js:14571)
    at angular.js:1455
    at Object.e [as invoke] (angular.js:4203)
    at d (angular.js:1453)
    at uc (angular.js:1473)
    at Jd (angular.js:1367)(anonymous function) @ angular.js:11655b.$get @ angular.js:8596(anonymous function) @ angular.js:13256a.$get.n.$eval @ angular.js:14466a.$get.n.$digest @ angular.js:14282a.$get.n.$apply @ angular.js:14571(anonymous function) @ angular.js:1455e @ angular.js:4203d @ angular.js:1453uc @ angular.js:1473Jd @ angular.js:1367(anonymous function) @ angular.js:26304a @ angular.js:2762c @ angular.js:3032
angular.js:11655 TypeError: newToast.scope.init is not a function
    at angular-toastr.tpls.js:169
    at angular.js:13248
    at e (angular.js:4924)
    at angular.js:5312
</code>

Can someone help?

**Comment by Foxandxss** [comment]
Reproduce your issue in a Plunker, but with what I see, I am not sure if it is related to this library or not.

**Comment by svuser1** [comment]
Thanks for getting back so quickly. Here is the plunker.

http://plnkr.co/edit/d4U98s7EmWzCQmmuf2Iw?p=preview

**Comment by Foxandxss** [comment]
The problem is your interceptor, it is broken.

An interceptor is a layer between angular and the destiny of your requests. Every time you use $http, $http will pass the `config` to `request` where you can tweak that config if needed or do other stuff before the request is actually made. Same happens with `response`, it also receives the $http `config` (and not `response` like you had) but this time, this is executed when the response comes back.

In both cases, you need to return the `config` or $http will lose it and fail. That is what happens in here, all your responses were broken so $http would never be able to request anything.

The reason it fails in here, is because the templates in angular (toastr has two templates) are also requested with `$http`, but since no $http request can be done with your setup, the templates will never arrive.

Fixing it is as simple as returning the config back.

http://plnkr.co/edit/nJE9ylf8fr0MJsGDUEQb?p=info

**Comment by svuser1** [comment]
You rock! Thanks a ton.
