### ISSUE TITLE
Cannot read property 'then' or undefined

### ISSUE THREAD

**Issue by mehmedju** [Foxandxss/angular-toastr#40]
Hi guys,

I followed all instructions mentioned in the documentation of using angular-toastr and I did everything step by step, but always I get the same error:

 **TypeError: Cannot read property 'then' of undefined
    at _createOrGetContainer (angular-toastr.tpls.js:120)
    at angular-toastr.tpls.js:139**

**Comment by Foxandxss** [comment]
If you're using angular 1.2.x you need to use the version 0.4.x.

On the other hand I recommend you to upgrade to 1.3.x, there shouldn't be too much hassle.

**Comment by selaromdotnet** [comment]
i am encountering the same problem after switching to the 1.2.x branch, which appears to still be using the $animate.enter() version that expects a promise.

I fixed this by modifying the angular.toaster.js from the 0.4.x branch on line 136 to the following:

			$animate.enter(container, target, null, function () {
				containerDefer.resolve();
			});

so that a callback is passed to the enter() method. this appears to fix the problem for me, but I'm curious what I'm doing wrong in grabbing the 1.2.x branch of toastr, as I'm using angular 1.2.9...

I'm sure it's just me screwing everything up, but making this change did fix the problem for me. let me know if I can provide any further details, thanks.
