### ISSUE TITLE
positionClass is considered a bad option?

### ISSUE THREAD

**Issue by Donniewiko** [Foxandxss/angular-toastr#67]
Hi,

I noticed the the positionClass cannot be overriden per toast
when i use:
```javascript
$http(...).error(function(e){
    toastr.error(e.exceptionMessage, e.message, { "positionClass": "toast-top-full-width"});
});
```
The positionclass will be removed from the options, which is done by:

```javascript
function cleanOptionsOverride(options) 
{
	var badOptions = ['containerId', 'iconClasses', 'maxOpened', 'newestOnTop',
	                'positionClass', 'preventDuplicates', 'templates'];
	for (var i = 0, l = badOptions.length; i < l; i++) {
		delete options[badOptions[i]];
	}

	return options;
}
````

I wonder why this is. I could set this as a config obviously, but i would like to override.

Kind regards

**Comment by Foxandxss** [comment]
The toasts themselves doesn't have the free will of being positioned where you want, instead they are created on a dynamically generated container which is the one using positionClass.

even if I delete `positionClass` from badOptions, it won't do anything.

Since the container gets deleted when there is no toasts, you can change the next's one position overriding the toastrConfig option.

Maybe I will consider multiple containers at once to be able to override positions by toast in a future.

**Comment by Donniewiko** [comment]
Hi,

Thanks for the quick reply.

It actually makes sense when i think about it. I should try that more
often...

Kind regards

Op 16:29 WO 8 Apr 2015 schreef Jesús Rodríguez Rodríguez <
notifications@github.com>:
