### ISSUE TITLE
Problem with PositionClass?

### ISSUE THREAD

**Issue by beaudetious** [Foxandxss/angular-toastr#73]
I am trying something very simple: displaying the toast in the bottom right.  Here's a simple demo:

http://plnkr.co/edit/gCBGINOVg1inrHqah8y3?p=preview

When I use the latest version (1.2.0 or 1.2.1) the positionClass configuration is ignored and the toast displays in the default top right position.  If I roll back to 0.5.2, then the positioning works as expected.  Is anyone else seeing this?

**Comment by Foxandxss** [comment]
So, I put that option as banned for concrete toasts. The `positionClass` is set on the global config instead of a concrete toasts.

On `0.5.2` I wasn't that strict with the options so setting `positionClass` on a toast and then if only and I say only a container wasn't there yet, it would create a container in that position. Then if you open a new toast while that container is still alive, it will popup in the same place.

So since letting a toast override the positionClass (only temporary, when the container gets deleted and a new toasts arises, it would fallback to default).

I need to think a proper way to handle this. Not sure if I want the new behavior or letting new toasts override it but maybe in a better way.

**Comment by beaudetious** [comment]
I understand. I should have checked out the change log or something.  I will use the global config option.  Thanks for the super fast reply.
