### ISSUE TITLE
Broken for Rails Assets ( https://rails-assets.org ) 

### ISSUE THREAD

**Issue by jaybloke** [Foxandxss/angular-toastr#94]
Appears to be an indentation anomaly here https://github.com/Foxandxss/angular-toastr/blob/master/dist/angular-toastr.css#L32 which breaks my SASS compilation.

After installing the equivalent angular-toastr gem from Rails Assets I receive this error:

Sass::SyntaxError: Invalid CSS after "    opacity": expected ";", was ": 0.4;"
  (in /home/deploy/app/releases/20150521061141/app/assets/stylesheets/application.css.scss:32)
/home/deploy/app/shared/bundle/ruby/2.1.0/gems/rails-assets-angular-toastr-1.4.0/app/assets/stylesheets/angular-toastr/angular-toastr.scss:32

Any quick fix available?

**Comment by Foxandxss** [comment]
A new version (1.4.1) will be released soon.

As a suggestion, don't use rails asset pipeline with Angular, that will shoot you in the foot sooner than later.

Better if you have two separate applications, one for rails as api and another one for Angular.

That is my personal suggestion, but the fix is there.

**Comment by jaybloke** [comment]
Thanks for the update.

The app I'm working on employs a rails api for the backend and angular for the front-end. As I have learned the hard way, trying to build two separate apps for the same site became a complete nightmare, i.e. integration, testing, deployment etc headache after headache! I switched to a single app approach using rails asset pipeline and now everything works harmoniously.

Cheers
